### ISSUE TITLE
No cache saved on Windows?

### ISSUE THREAD

**Issue by SimonHeybrock** [hendrikmuhs/ccache-action#55] opened 2022-03-24 10:05 UTC
Having trouble with ccache on Windows (thanks for adding support!). My cache is empty for now, so no hits are reported. But there *does* appear to be something in the cache (and my cmake found ccache): `  Cache size (GB):  0.09 / 0.50 (18.79 %)`. Yet, nothing is uploaded.

This is the output I get:

```
+ ccache -s -v
Summary:
  Cache directory:  D:\a\scipp\scipp\.ccache
  Primary config:   C:\Users\runneradmin/ccache/ccache.conf
  Secondary config: /usr/local/etc/ccache.conf
  Stats updated:    03/24/22 09:39:15
  Hits:                0 /  395 (0.00 %)
    Direct:            0 /  395 (0.00 %)
    Preprocessed:      0 /  395 (0.00 %)
  Misses:            395
    Direct:          395
    Preprocessed:    395
Primary storage:
  Hits:                0 /  790 (0.00 %)
  Misses:            790
  Cache size (GB):  0.09 / 0.50 (18.79 %)
  Files:             790
Not saving cache because no objects are cached.
```

**Comment by hendrikmuhs** [comment] 2022-03-24 10:36
@jonashaag can you have a look?

**Comment by jonashaag** [comment] 2022-03-24 11:26
@SimonHeybrock can you please share a link to an action run?

**Comment by SimonHeybrock** [comment] 2022-03-24 11:37
@jonashaag See https://github.com/scipp/scipp/actions/runs/2033203851.

**Comment by jonashaag** [comment] 2022-03-24 12:04
Found it, bad regex `/Files:.+0/`, I wanted to match `Files: 0` but it also matches something like `Files: 350` 🤦

**Comment by jonashaag** [comment] 2022-03-24 12:07
Added a fix here https://github.com/hendrikmuhs/ccache-action/pull/54

**Comment by hendrikmuhs** [comment] 2022-03-24 12:56
@jonashaag #54 is still marked as draft. By accident or intentional? I like to either split out the fix or get #54 ready to go.

**Closed** 2022-03-24 20:29 UTC

**Comment by alemuntoni** [comment] 2022-10-28 12:43
Hello, I am still having this issue: `Not saving cache because no objects are cached.` on windows.
I just made a small repo example to reproduce it: https://github.com/alemuntoni/ccache-hello-world)

[here](https://github.com/alemuntoni/ccache-hello-world/actions/runs/3345460757/workflow) the workflow file and [here](https://github.com/alemuntoni/ccache-hello-world/actions/runs/3345460757/jobs/5541013114) the workflow run.

You can see that I made also similar workflows for linux and macos, which work fine.
 
Am I doing something wrong?

**Comment by jonashaag** [comment] 2022-10-28 13:07
Did you check if some of the other windows related bug reports in this repo apply to your use case?

**Comment by hendrikmuhs** [comment] 2022-10-28 13:35
The important info from your run:

```
  C:\ProgramData\Chocolatey\bin\ccache.exe -s
  cache directory                     C:\Users\runneradmin\AppData\Roaming/ccache
  primary config                      C:\Users\runneradmin\AppData\Roaming/ccache/ccache.conf
  secondary config (readonly)         R:/winlibs64_stage/inst_ccache-4.3/etc/ccache.conf
  cache hit (direct)                     0
  cache hit (preprocessed)               0
  cache miss                             0
  cache hit rate                      0.00 %
  cleanups performed                     0
  files in cache                         0
  cache size                           0.0 kB
  max cache size                       5.0 GB
```

Ccache isn't called, you should have at least 1 cache miss.

FWIW, a closed issue isn't the proper place to discuss your problem, IMO it is different to the one of the original thread opener. Either create a new issue or open a thread under discussions.
